version: '3.8'
services:
  db-1:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=password1
      - MYSQL_DATABASE=db-1
    volumes:
      - type: volume
        source: db-1
        target: /var/lib/mysql
    ports:
      - '13306:3306'
  db-2:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user2
      - MYSQL_PASSWORD=password2
      - MYSQL_DATABASE=db-2
    volumes:
      - type: volume
        source: db-2
        target: /var/lib/mysql
    ports:
      - '23306:3306'

volumes:
  db-1:
  db-2:
