service: nestjs-multiple-databases

plugins:
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs18.x
  stage: ${opt:stage,self:custom.defaultStage}
  profile: ${self:custom.otherfile.enviroment.${self:provider.stage}.profile}
  deploymentBucket:
    name: ${self:custom.otherfile.enviroment.${self:provider.stage}.bucket_name}

custom:
  defaultStage: dev
  otherfile:
    enviroment:
      dev: ${file(./conf/env/dev.yml)}
      prod: ${file(./conf/env/prod.yml)}

functions:
  main:
    handler: dist/main.handler
    name: ${self:provider.stage}-${self:service}
    description: Lambda API multiple databases ${self:custom.otherfile.enviroment.${self:provider.stage}.path}
    role: ${self:custom.otherfile.enviroment.${self:provider.stage}.role}
    events:
      - http:
          method: ANY
          path: /
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
            allowCredentials: true

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/@internal/prisma-second/client/libquery_engine-*'
    - 'node_modules/@internal/prisma-second/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
